const sampleListings = [
    {
        title: "Wedding Lehenga",
        description:
            "Red bridal lehenga with heavy gold embroidery, structured blouse, and embroidered dupatta for premium wedding ceremonies.",
        image: "https://imgmediagumlet.lbb.in/media/2024/11/6736e4b1b25c7c176a7247db_1731650737253.jpg",
        pricePerDay: 1500,
        location: "Bhopal",
        category: "Lehenga",
        occasion: "Wedding",
        size: ["M", "L"],
        fitType: "Regular",
        rentalStatus: "available",
        rating: 4.6,
    },
    {
        title: "Kurta Pajama Set",
        description:
            "Elegant silk kurta pajama set suitable for festive occasions and traditional gatherings.",
        image: "https://rajanyas.com/cdn/shop/files/Untitleddesign-2023-09-26T115227.454.png?v=1695711580&width=1946",
        pricePerDay: 1200,
        location: "Indore",
        category: "Kurta Pajama",
        occasion: "Festive",
        size: ["M", "L", "XL"],
        fitType: "Relaxed",
        rentalStatus: "available",
        rating: 4.4,
    },
    {
        title: "Formal Sherwani",
        description:
            "Classic formal sherwani with intricate embroidery, designed for weddings and receptions.",
        image: "https://www.parivarceremony.com/media/catalog/product/cache/14a1553305c404c221b3f13f50c007dd/p/1/p1251mw01-1.jpg",
        pricePerDay: 1800,
        location: "Delhi",
        category: "Sherwani",
        occasion: "Wedding",
        size: ["L", "XL"],
        fitType: "Slim",
        rentalStatus: "reserved",
        rating: 4.7,
    },
    {
        title: "Anarkali Gown",
        description:
            "Flowing Anarkali gown with sequin detailing, ideal for receptions and festive evenings.",
        image: "https://www.meerasplussizestore.com/cdn/shop/products/Wine-sequin-anarkali-SCL_6618.jpg?v=1750317715&width=2000",
        pricePerDay: 2500,
        location: "Jaipur",
        category: "Anarkali",
        occasion: "Reception",
        size: ["M", "L"],
        fitType: "Regular",
        rentalStatus: "available",
        rating: 4.8,
    },
    {
        title: "Designer Wedding Sherwani",
        description:
            "Premium designer sherwani for grooms, delivering a regal silhouette and luxury finish.",
        image: "https://www.shaadibaraati.com/vendors-profile/79a09ec64d2c064c39c34b09376c907e.jpg",
        pricePerDay: 2200,
        location: "Lucknow",
        category: "Sherwani",
        occasion: "Wedding",
        size: ["M", "L"],
        fitType: "Slim",
        rentalStatus: "rented",
        rating: 4.9,
    },
    {
        title: "Three-Piece Suit",
        description:
            "Tailored three-piece suit suitable for corporate events, weddings, and formal occasions.",
        image: "https://img.lazcdn.com/g/p/8a9c076aa59badd373feb29baeb9cbac.jpg_webp_720x720q80.jpg",
        pricePerDay: 2000,
        location: "Mumbai",
        category: "Suit",
        occasion: "Corporate",
        size: ["M", "L", "XL"],
        fitType: "Slim",
        rentalStatus: "available",
        rating: 4.5,
    },
    {
        title: "Classic Bandhgala Suit",
        description:
            "Minimalist bandhgala suit offering a refined ethnic look for formal and festive events.",
        image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
        pricePerDay: 1600,
        location: "Jodhpur",
        category: "Bandhgala",
        occasion: "Formal",
        size: ["M", "L"],
        fitType: "Regular",
        rentalStatus: "available",
        rating: 4.3,
    },
];

module.exports = { data: sampleListings };
