const sampleListings = [
    {
        title: "Wedding Lehenga",
        description:
            "Red bridal lehenga with heavy gold embroidery, structured blouse, and embroidered dupatta for premium wedding ceremonies.",
        image: "https://images.unsplash.com/photo-1583391733959-b15132ceee0f?w=600&q=80",
        pricePerDay: 1500,
        location: "Bhopal",
        category: "Lehenga",
        occasion: "Wedding",
        size: ["M", "L"],
        fitType: "Regular",
        rentalStatus: "available",
        rating: 4.6,
    },
    {
        title: "Kurta Pajama Set",
        description:
            "Elegant silk kurta pajama set suitable for festive occasions and traditional gatherings.",
        image: "https://images.unsplash.com/photo-1596455607563-ad6193f76b19?w=600&q=80",
        pricePerDay: 1200,
        location: "Indore",
        category: "Kurta Pajama",
        occasion: "Festive",
        size: ["M", "L", "XL"],
        fitType: "Relaxed",
        rentalStatus: "available",
        rating: 4.4,
    },
    {
        title: "Formal Sherwani",
        description:
            "Classic formal sherwani with intricate embroidery, designed for weddings and receptions.",
        image: "https://images.unsplash.com/photo-1610030469983-98e5509c5328?w=600&q=80",
        pricePerDay: 1800,
        location: "Delhi",
        category: "Sherwani",
        occasion: "Wedding",
        size: ["L", "XL"],
        fitType: "Slim",
        rentalStatus: "available",
        rating: 4.7,
    },
    {
        title: "Anarkali Gown",
        description:
            "Flowing Anarkali gown with sequin detailing, ideal for receptions and festive evenings.",
        image: "https://images.unsplash.com/photo-1610486663273-0f1ed04505f9?w=600&q=80",
        pricePerDay: 2500,
        location: "Jaipur",
        category: "Anarkali",
        occasion: "Reception",
        size: ["M", "L"],
        fitType: "Regular",
        rentalStatus: "available",
        rating: 4.8,
    },
    {
        title: "Designer Wedding Sherwani",
        description:
            "Premium designer sherwani for grooms, delivering a regal silhouette and luxury finish.",
        image: "https://images.unsplash.com/photo-1598004576974-bc5db0c6ff74?w=600&q=80",
        pricePerDay: 2200,
        location: "Lucknow",
        category: "Sherwani",
        occasion: "Wedding",
        size: ["M", "L"],
        fitType: "Slim",
        rentalStatus: "rented",
        rating: 4.9,
    },
    {
        title: "Three-Piece Suit",
        description:
            "Tailored three-piece suit suitable for corporate events, weddings, and formal occasions.",
        image: "https://images.unsplash.com/photo-1594938298596-fdd2c98d6dd1?w=600&q=80",
        pricePerDay: 2000,
        location: "Mumbai",
        category: "Suit",
        occasion: "Corporate",
        size: ["M", "L", "XL"],
        fitType: "Slim",
        rentalStatus: "available",
        rating: 4.5,
    },
    {
        title: "Classic Bandhgala Suit",
        description:
            "Minimalist bandhgala suit offering a refined ethnic look for formal and festive events.",
        image: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=600&q=80",
        pricePerDay: 1600,
        location: "Jodhpur",
        category: "Bandhgala",
        occasion: "Formal",
        size: ["M", "L"],
        fitType: "Regular",
        rentalStatus: "available",
        rating: 4.3,
    },
];

module.exports = { data: sampleListings };
